apiVersion: v1
kind: PersistentVolume
metadata:
  name: chicago-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/chicago-taxi-cab-data"
