studyName: tfjob-example
owner: crd
optimizationtype: minimize
objectivevaluename: loss
optimizationgoal: 0.01
requestcount: 1
metricsnames:
 - loss
parameterconfigs:
 - name: --learning_rate
   parametertype: double
   feasible:
     min: "0.01"
     max: "0.05"
 - name: --batch_size
   parametertype: int
   feasible:
     min: "100"
     max: "200"
 - name: --num_epochs
   parametertype: int
   feasible:
     min: "1"
     max: "10"
