version: "2"

services:
  dfabricinfluxd:
    image: ocdr/dfabric-influxdb:v0.2
    container_name: dfabstats
    restart: always
    environment:
      REST_SERVER_ENDPOINT: http://<MCPU IP>:8080/v1/
    volumes:
      - "/var/lib/influxdb/:/var/lib/influxdb"
    ports:
      - "8086:8086"
  dfabricuiserver:
    image: ocdr/dfabric-uiserver:v0.2
    container_name: dfabui
    restart: always
    environment:
      REST_SERVER_ENDPOINT: http://<MCPU IP>:8080/v1/
      STATS_ENDPOINT: http://<STATS SERVER IP>:8086/
    ports:
      - "3000:3000"