apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oc-device-plugin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oc-device-plugin
  namespace: device-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oc-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oc-device-plugin
subjects:
- kind: ServiceAccount
  name: oc-device-plugin
  namespace: device-ns
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: nvidia-device-plugin-ds
  name: oc-device-plugin
  namespace: device-ns
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: oc/test-nvidia:v1
        imagePullPolicy: IfNotPresent
        name: nvidia-device-plugin-ctr
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugin
      serviceAccount: oc-device-plugin
      serviceAccountName: oc-device-plugin
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: ""
        name: device-plugin

