apiVersion: v1
kind: Pod
metadata:
  name: inference
  labels:
    name: inference
spec:
  containers:
  - name: inference
    image: inference:v1
---
apiVersion: v1
kind: Service
metadata:
  name: inference
spec:
  type: LoadBalancer
  selector:
    name: inference
  ports:
  - name: http
    port: 9000
    nodePort: 31123
    targetPort: 9000
